(()=>{
const stage=document.querySelector('.device-stage'),screen=document.querySelector('.device-live-screen');if(!stage||!screen)return;
// Project the 640px interface onto the four inner-glass corners of the concept render.
const corners=[[332,230],[950,207],[862,925],[209,883]];
function solve(A,b){const n=b.length;for(let i=0;i<n;i++){let pivot=i;for(let j=i+1;j<n;j++)if(Math.abs(A[j][i])>Math.abs(A[pivot][i]))pivot=j;[A[i],A[pivot]]=[A[pivot],A[i]];[b[i],b[pivot]]=[b[pivot],b[i]];const div=A[i][i];if(Math.abs(div)<1e-12)throw Error('Invalid screen projection');for(let j=i;j<n;j++)A[i][j]/=div;b[i]/=div;for(let k=0;k<n;k++)if(k!==i){const f=A[k][i];for(let j=i;j<n;j++)A[k][j]-=f*A[i][j];b[k]-=f*b[i]}}return b}
function position(){const scale=stage.clientWidth/1254;if(!scale)return;const from=[[0,0],[640,0],[640,640],[0,640]],A=[],b=[];from.forEach(([x,y],i)=>{const [u,v]=corners[i].map(q=>q*scale);A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)});const h=solve(A,b);screen.style.transform='matrix3d('+[h[0],h[3],0,h[6],h[1],h[4],0,h[7],0,0,1,0,h[2],h[5],0,1].join(',')+')';screen.classList.add('is-positioned')}
new ResizeObserver(position).observe(stage);position();
const scenes=[{key:'receipt',name:'Receipt',kicker:'ALL SORTED.',title:'Your receipt.<br>Minus the paper.',detail:'Thank you for stopping by.',instruction:'Scan to take it with you.'},{key:'gift',name:'Little surprise',kicker:'CUSTOMER NO. 10,000',title:'A little surprise.<br>Just for you.',detail:'Today, the treat is on us.',instruction:'Scan to discover your gift.'},{key:'loyalty',name:'Loyalty',kicker:'NICE TO SEE YOU AGAIN.',title:'One visit closer.<br>One more reason.',detail:'Your next reward is waiting.',instruction:'Scan to open your loyalty page.'},{key:'menu',name:'Menu',kicker:'SOMETHING GOOD AWAITS.',title:'What are you<br>in the mood for?',detail:'Take a look at today’s menu.',instruction:'Scan to find your favourite.'}];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let index=0,playing=!reduced.matches,timer=null,visible=true;const frame=screen.querySelector('.screen-frame'),caption=document.querySelector('#screen-caption'),play=document.querySelector('#screen-play'),dots=[...document.querySelectorAll('[data-scene]')];
function render(){const s=scenes[index];frame.dataset.screen=s.key;frame.querySelector('.screen-kicker').textContent=s.kicker;frame.querySelector('.screen-heading').innerHTML=s.title;frame.querySelector('.screen-detail').textContent=s.detail;frame.querySelector('.screen-instruction').textContent=s.instruction;caption.textContent='0'+(index+1)+' / '+s.name;dots.forEach((d,i)=>d.setAttribute('aria-pressed',String(index===i)));if(!reduced.matches)frame.querySelector('.screen-scene').animate([{opacity:0,transform:'translateY(7px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,easing:'ease-out'});}
function schedule(){clearTimeout(timer);if(playing&&visible&&!document.hidden)timer=setTimeout(()=>{index=(index+1)%scenes.length;render();schedule()},4200)}
function update(){play.textContent=playing?'Pause':'Play';play.setAttribute('aria-label',playing?'Pause screen preview':'Play screen preview');schedule()}
play.addEventListener('click',()=>{playing=!playing;update()});dots.forEach((d,i)=>d.addEventListener('click',()=>{index=i;playing=false;render();update()}));document.addEventListener('visibilitychange',schedule);new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;schedule()},{threshold:.1}).observe(stage);reduced.addEventListener('change',()=>{if(reduced.matches){playing=false;update()}});render();update();
})();